/*
 * Open Teradata Viewer ( files comparator plugin )
 * Copyright (C) 2011, D. Campione
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.files_comparator.ui;

/**
 *
 *
 * @author D. Campione
 * 
 */
public class FolderDiffForm extends AbstractContentPanel {

    private static final long serialVersionUID = 5258706607553106561L;

    /** Creates new form FolderDiffForm */
    public FolderDiffForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        folder1Label = new org.files_comparator.ui.swing.DiffLabel();
        folder2Label = new org.files_comparator.ui.swing.DiffLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        folderTreeTable = new org.files_comparator.ui.swing.table.FilesComparatorTreeTable();
        onlyRightButton = new javax.swing.JToggleButton();
        leftRightChangedButton = new javax.swing.JToggleButton();
        onlyLeftButton = new javax.swing.JToggleButton();
        leftRightUnChangedButton = new javax.swing.JToggleButton();
        hierarchyComboBox = new javax.swing.JComboBox();
        expandAllButton = new javax.swing.JButton();
        collapseAllButton = new javax.swing.JButton();
        deleteLeftButton = new javax.swing.JButton();
        copyToLeftButton = new javax.swing.JButton();
        copyToRightButton = new javax.swing.JButton();
        deleteRightButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        compareButton = new javax.swing.JButton();

        folder1Label.setText("Left name of directory");

        folder2Label.setText("Right name of directory");

        jScrollPane1.setViewportView(folderTreeTable);

        onlyRightButton.setText("R");

        leftRightChangedButton.setText("LR");

        onlyLeftButton.setText("L");

        leftRightUnChangedButton.setText("Un");

        hierarchyComboBox.setModel(new javax.swing.DefaultComboBoxModel(
                new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        expandAllButton.setText("Exp");

        collapseAllButton.setText("Col");

        deleteLeftButton.setText("DL");
        deleteLeftButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        copyToLeftButton.setText("CL");
        copyToLeftButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        copyToRightButton.setText("CR");
        copyToRightButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        deleteRightButton.setText("DR");
        deleteRightButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        refreshButton.setText("RS");
        refreshButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        compareButton.setText("CO");
        compareButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
                this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .add(layout
                                .createParallelGroup(
                                        org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING,
                                        layout.createSequentialGroup()
                                                .add(layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(folder1Label,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(layout
                                                                .createSequentialGroup()
                                                                .add(expandAllButton)
                                                                .addPreferredGap(
                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(collapseAllButton)
                                                                .addPreferredGap(
                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(hierarchyComboBox,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(compareButton)
                                                .addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(refreshButton)
                                                .add(59, 59, 59)
                                                .add(deleteLeftButton)
                                                .addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(copyToLeftButton)
                                                .add(18, 18, 18)
                                                .add(copyToRightButton)
                                                .addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(deleteRightButton)
                                                .addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED,
                                                        199, Short.MAX_VALUE)
                                                .add(layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(layout
                                                                .createSequentialGroup()
                                                                .add(onlyLeftButton)
                                                                .addPreferredGap(
                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(leftRightChangedButton)
                                                                .addPreferredGap(
                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(onlyRightButton)
                                                                .addPreferredGap(
                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(leftRightUnChangedButton))
                                                        .add(folder2Label,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(jScrollPane1,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        875, Short.MAX_VALUE))
                        .addContainerGap()));

        layout.linkSize(new java.awt.Component[]{leftRightChangedButton,
                leftRightUnChangedButton, onlyLeftButton, onlyRightButton},
                org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(layout
                .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout
                        .createSequentialGroup()
                        .addContainerGap()
                        .add(layout
                                .createParallelGroup(
                                        org.jdesktop.layout.GroupLayout.LEADING)
                                .add(folder1Label,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(folder2Label,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout
                                .createParallelGroup(
                                        org.jdesktop.layout.GroupLayout.CENTER)
                                .add(expandAllButton)
                                .add(collapseAllButton)
                                .add(hierarchyComboBox,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(compareButton).add(refreshButton)
                                .add(deleteLeftButton).add(copyToLeftButton)
                                .add(copyToRightButton).add(deleteRightButton)
                                .add(onlyLeftButton)
                                .add(leftRightChangedButton)
                                .add(onlyRightButton)
                                .add(leftRightUnChangedButton))
                        .addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                362, Short.MAX_VALUE).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton collapseAllButton;
    protected javax.swing.JButton compareButton;
    protected javax.swing.JButton copyToLeftButton;
    protected javax.swing.JButton copyToRightButton;
    protected javax.swing.JButton deleteLeftButton;
    protected javax.swing.JButton deleteRightButton;
    protected javax.swing.JButton expandAllButton;
    protected org.files_comparator.ui.swing.DiffLabel folder1Label;
    protected org.files_comparator.ui.swing.DiffLabel folder2Label;
    protected org.files_comparator.ui.swing.table.FilesComparatorTreeTable folderTreeTable;
    protected javax.swing.JComboBox hierarchyComboBox;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JToggleButton leftRightChangedButton;
    protected javax.swing.JToggleButton leftRightUnChangedButton;
    protected javax.swing.JToggleButton onlyLeftButton;
    protected javax.swing.JToggleButton onlyRightButton;
    protected javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables

}
